### ISSUE TITLE
error problem 

### ISSUE THREAD

**Issue by LouisLin0706** [zj-wukewei/Hot#11]
03-05 21:57:58.381 3140-3140/com.avtime.avtime E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.avtime.avtime, PID: 3140
                                                                 java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                     at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:114)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                  Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
                                                                     at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:186)
                                                                     at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
                                                                     at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:72)
                                                                     at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:268)
                                                                     at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:824)
                                                                     at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:585)
                                                                     at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:574)
                                                                     at rx.internal.operators.OperatorMerge$InnerSubscriber.onError(OperatorMerge.java:858)
                                                                     at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
                                                                     at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
                                                                     at rx.Observable.unsafeSubscribe(Observable.java:9861)
                                                                     at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:250)
                                                                     at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:147)
                                                                     at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
                                                                     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:227)
                                                                     at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
                                                                     at android.os.Handler.handleCallback(Handler.java:739) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                     at android.os.Looper.loop(Looper.java:148) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                  Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
                                                                     at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:186) 
                                                                     at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115) 
                                                                     at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:72) 
                                                                     at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:268) 
                                                                     at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:824) 
                                                                     at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:585) 
                                                                     at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:574) 
                                                                     at rx.internal.operators.OperatorMerge$InnerSubscriber.onError(OperatorMerge.java:858) 
                                                                     at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44) 
                                                                     at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28) 
                                                                     at rx.Observable.unsafeSubscribe(Observable.java:9861) 
                                                                     at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:250) 
                                                                     at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:147) 
                                                                     at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77) 
                                                                     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:227) 
                                                                     at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107) 
                                                                     at android.os.Handler.handleCallback(Handler.java:739) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                     at android.os.Looper.loop(Looper.java:148) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                  Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
                                                                     at android.util.Log.getStackTraceString(Log.java:338)
                                                                     at com.android.internal.os.RuntimeInit.Clog_e(RuntimeInit.java:61)
                                                                     at com.android.internal.os.RuntimeInit.-wrap0(RuntimeInit.java)
                                                                     at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:86)
                                                                     at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                     at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
                                                                     at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:118)
                                                                     at android.os.Handler.handleCallback(Handler.java:739) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                     at android.os.Looper.loop(Looper.java:148) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                  Caused by: com.wkw.common_lib.rx.error.ServerException
                                                                     at com.wkw.common_lib.rx.RxResultHelper$1$1.call(RxResultHelper.java:28)
                                                                     at com.wkw.common_lib.rx.RxResultHelper$1$1.call(RxResultHelper.java:20)
                                                                     at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
                                                                     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:227)
                                                                     at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
                                                                     at android.os.Handler.handleCallback(Handler.java:739) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                     at android.os.Looper.loop(Looper.java:148) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                  Caused by: java.lang.ClassCastException: com.wkw.common_lib.rx.error.DefaultErrorBundle cannot be cast to com.wkw.common_lib.rx.error.ServerException
                                                                     at com.wkw.common_lib.rx.error.ErrorHanding.handleError(ErrorHanding.java:29)
                                                                     at com.wkw.common_lib.rx.RxSubscriber.onError(RxSubscriber.java:26)
                                                                     at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:152)
                                                                     at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
                                                                     at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:72)
                                                                     at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:268)
                                                                     at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:824)
                                                                 	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitL

**Comment by zj-wukewei** [comment]
已解决
